# Generated by Django 2.2.10 on 2020-07-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ensurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plan',
            table='planes',
        ),
    ]
