# Generated by Django 2.2.10 on 2020-07-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ensurance', '0004_auto_20200721_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='pregunta3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='pregunta1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='pregunta2',
            field=models.BooleanField(default=False),
        ),
    ]
