# Generated by Django 2.2.10 on 2020-07-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ensurance', '0007_auto_20200721_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='beneficiarios',
            field=models.CharField(default='POR DEFINIR', max_length=3),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tipodoc',
            field=models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('CI', 'Cedula de Extranjeria')], max_length=20),
        ),
    ]
