# Generated by Django 2.2.10 on 2020-07-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ensurance', '0008_auto_20200721_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='beneficiarios',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
