# Generated by Django 2.2.10 on 2020-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ensurance', '0009_auto_20200721_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=20)),
                ('tipodoc', models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('CI', 'Cedula de Extranjeria')], max_length=20)),
                ('fechanacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
